title: Klimaentscheid Kaiserslautern
tagline: Landkreis und Stadt Kaiserslautern klimaneutral!
url: https://klimalautern.de

author:
  name: KlimaLautern - Klimaentscheid Kaiserslautern
  url: https://klimalautern.de
  twitter: KlimaLautern

plugins:
  - jekyll-feed

markdown: kramdown
