title: KlimaLautern
tagline: Kaiserslautern klimaneutral!
url: https://klimaentscheid-kaiserslautern.github.io/

author:
  name: KlimaLautern
  url: https://klimaentscheid-kaiserslautern.github.io/
  twitter: KlimaLautern

markdown: kramdown
