title: Klimaentscheid Kaiserslautern
tagline: Landkreis und Stadt Kaiserslautern klimaneutral!
url: https://klimaentscheid-kaiserslautern.github.io/

author:
  name: KlimaLautern - Klimaentscheid Kaiserslautern
  url: https://klimalautern.de/
  twitter: KlimaLautern

markdown: kramdown
